# language
language: java

# jdk：oraclejdk8 has LICENSE problem
jdk: openjdk8

# install and maven install
install: true

# process codecov 的检查
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 547f5cf4-f7e8-462e-b84c-7ef5ccfaa70a

# 提高构建速度
cache:
  directories:
  - $HOME/.m2

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

