# language
language: java

# jdk：oraclejdk8 has LICENSE problem
jdk: openjdk8

env:
  CATALINA_BASE=/home/travis

sudo: false
# install and maven install
install: true

# process maven codecov 的检查
script:
  - mvn install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

# 提高构建速度
cache:
  directories:
  - $HOME/.m2

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

